config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user 
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article 
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
  end 

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}

    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                        length: {minimum: 3, maximum: 25}, 
                        uniqueness: { case_sensitive: false }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                        length: {maximum: 105},
                        uniqueness: { case_sensitive: false },
                        format: { with: VALID_EMAIL_REGEX }
                      
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?, :require_admin

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end

    def require_user
      if !logged_in?
        flash[:alert] = "You must log in to perfon that action"
        redirect_to login_path
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 6)
  end

  def new
    @article = Article.new
  end

  def edit
  end
  
  def create
    #render plain: params[:article]
    @article = Article.new(article_params)
    @article.user = current_user
    


    if  @article.save
      flash[:notice] = "Article created successfully!"
      @article = Article.last
      redirect_to article_path(@article)
    else
      render 'new'
    end
    #render plain: @article.inspect
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated correctly"
      redirect_to @article
    else 
     render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,:description, category_ids: [] )

  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You are not allowed to do that"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

    def new
      @category = Category.new
    end

    def index
      #@categories = Category.all
      @categories = Category.paginate(page: params[:page], per_page: 6) 
    end

    def show
      @category = Category.find(params[:id])
      @category_articles = @category.articles.paginate(page: params[:page], per_page: 6)
    end

    

    def create
        @category = Category.new(category_params)

        if @category.save
          flash[:notice] = "Categoria hecha"
          redirect_to categories_path
        else
          render 'new'
        end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        flash[:notice] = "Change created"
        redirect_to category_path(@category)
      else
        render 'edit'
      end
    end


    private 
    def category_params
      params.require(:category).permit(:name)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "Please log in"
        redirect_to categories_path
      end
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Sesión iniciada"
            redirect_to user
        else
          flash.now[:alert] = "Incorrect user / password"
          render 'new'
        end

    end

    def destroy
      session[:user_id] = nil
      flash[:notice] = "Log out"
      redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
      @user = User.new
    end

    def index
      @users = User.paginate(page: params[:page], per_page: 6)

    end

    def show
      @articles = @user.articles.paginate(page: params[:page], per_page: 6)
    end

    def edit
    end

    def update
      if @user.update(user_params)
        flash[:notice] = "Tu cuenta ha sido actualizada"
        redirect_to @user
      else
        render 'edit'
      end
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Bienvenido a alphablog #{@user.username}"
        redirect_to root_path
      else
        render 'new'
      end
    end

    def destroy
      @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:alert] = "You have destroyed your account"
      redirect_to articles_path
    end

    private 
    def user_params
      params.require(:user).permit(:username,:email,:password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if @user != current_user && !current_user.admin?
        flash[:alert] = "You are not allowed to do that"
        redirect_to users_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options ={ size: 80})
      email_address = user.email
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt:user.username, class:"profile-img")
    end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="row">
    <% obj.each do |article| %>
        <div class="card text-center col-sm-4">
            <div class="card-header">
                Publicado por: <%= link_to article.user.username, user_path(article.user) %>
            </div>
            
            <div class="card-body">
                <h5 class="card-title"> <%= article.title %> </h5>
                <p class="card-text"> <%= truncate(article.description, length: 50) %> </p>
                <%= link_to 'Show', article_path(article.id), class: "btn btn-outline-success" %>
                <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to 'Editar', edit_article_path(article.id), class: "btn btn-outline-info" %>
                <%= link_to 'Delete', article_path(article.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                <% end %>

                <% if article.categories.any? %>
                    <div class="card-text text-left mt-5"> Categorias:
                        <% article.categories.each do |category| %>
                            <span class="badge"> <%= link_to category.name, category_path(category) %> &nbsp; </span>
                        <% end %>
                    </div>
                <% end %>

            </div>
            <div class="card-footer text-muted">
                Last edition <%= time_ago_in_words(article.updated_at) %> ago
            </div>  
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container p-4  shadow mb-5 rounded" id="new-edit-form">
    <%= render 'shared/errors', obj: @article %>
    
    <%= form_with(model: @article,  local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
                <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Titulo del artículo" %>
            </div>
            
        </div>
        <div class="form-group row">
            <%= f.label :description, class: "col-2 col-form-label  text-light" %>
            <div class="col-10">
                <%= f.text_area :description, rows: 10 , class: "form-control shadow rounded", placeholder: "Descripción el articulo" %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox")  + cb.text} %>
            <% end %>
        </div>

        <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg shadow rounded" %>
        </div>
    <% end %>
</div>
<%= link_to '[Cancel and return to the articles]', articles_path, class: "text-info text-center" %>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Editar Artículo</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articulos publicados</h1>

<%= render 'shared/pagination', obj: @articles %>

<%= render 'articles', obj: @articles %>

<%= render 'shared/pagination', obj: @articles %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Articulo nuevo</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container justify-content">
    <h2 class="text-center p-4"><%= @article.title %></h2>
    <div class="card text-center col-sm-12">
        <div class="card-header">
            Publicado por: <%= link_to @article.user.username, user_path(@article.user) %><br>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>

        </div>
        <div class="card-body">
            <div class="card-text text-left mb-4"> <%= simple_format(@article.description) %> </div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                <%= link_to 'Editar', edit_article_path(@article.id), class: "btn btn-outline-info" %>
                <%= link_to 'Delete', article_path(@article.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>

            <% if @article.categories.any? %>
                <div class="card-text text-left mt-5"> Categorias:
                <% @article.categories.each do |category| %>
                    <span class="badge"> <%= link_to category.name, category_path(category) %> &nbsp; </span>
                <% end %>
                 </div>
            <% end %>
        </div>


        
        <div class="card-footer text-muted text-center">
            Created <%= time_ago_in_words(@article.created_at) %> ago,
            Last edition <%= time_ago_in_words(@article.updated_at) %> ago
        </div>  
    </div>
</div>

app/views/categories/_form.html.erb
<div class="container p-4  shadow mb-5 rounded" id="new-edit-form">
    <%= render 'shared/errors', obj: @category %>
    
    <%= form_with(model: @category,  local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :name, "Category name" , class: "col-2 col-form-label text-light" %>
            <div class="col-10">
                <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Ingrese una categoria" %>
            </div>
        </div>
        

        <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg shadow rounded" %>
        </div>
    <% end %>
</div>
<%= link_to '[Cancel and return to the home]', users_path, class: "text-info text-center" %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Editar articulo</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Articulos publicados</h1>

<%= render 'shared/pagination', obj: @categories %>

<div class="row">
    <% @categories.each do |category| %>
        <div class="card text-center col-sm-4">
            <div class="card-body">
                <h5 class="card-title"> <%= link_to category.name, category_path(category), class: "text-success" %> </h5>
                <li><small> <%= pluralize(category.articles.count, "article") %> </small></li>
                <% if logged_in? && current_user.admin? %>
                    <%= link_to 'Editar', edit_category_path(category.id), class: "btn btn-outline-info" %>
                <% end %>
            </div>
            
            <div class="card-footer text-muted">
                Created <%= time_ago_in_words(category.created_at) %> ago
            </div>  
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a category</h1>
<%= render 'form' %>
<%= link_to '[Cancel and return to the home]', users_path, class: "text-info text-center" %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Categoria: <%= @category.name %></h1>
<% if logged_in? && current_user.admin? %>
    <%= link_to 'Editar', edit_category_path(@category.id), class: "btn btn-outline-info" %>
<% end %>

<%= render 'shared/pagination', obj: @category_articles %>

<%= render 'articles/articles', obj: @category_articles %>

<%= render 'shared/pagination', obj: @category_articles %>

app/views/layouts/_footer.html.erb
<footer id="footer">
    <div class="container text-center">
      <small>Khinoda &trade; Producto nuevo!</small>
    </div>
    
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show pb-4" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'α-Blog', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to 'Home', root_path, class:"nav-link" %> <span class="sr-only">(current)</span>
            </li>

            <li class="nav-item">
                <%= link_to 'Tabla de articulos', articles_path, class:"nav-link" %>
            </li>
            

            <li class="nav-item">
                <%= link_to 'Usuarios', users_path, class:"nav-link" %>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Articulos
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <% if logged_in? %>
                        <%= link_to 'Nuevo', new_article_path, class: "dropdown-item" %>
                    <% end %>
                    <%= link_to 'Ver todos', articles_path, class: "dropdown-item" %>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item disabled" href="#">Algo que no sirve</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categorias
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    
                    <%= link_to 'Todas las categorias...', categories_path, class: "dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <% Category.all.each do |category|%>
                    <%= link_to category.name, category_path(category), class: "dropdown-item" %>
                    <% end %>
                    <% if logged_in? && current_user.admin? %>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'Crear nueva categoria', new_category_path , class: "dropdown-item" %>
                    <% end %>
                </div>
            </li>


            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     <%= "Admin" if current_user.admin? %>  Profile <%= current_user.username %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'Mi perfil', user_path(current_user) , class: "dropdown-item" %>
                    <%= link_to 'Edit my profile', edit_user_path(current_user), class: "dropdown-item" %>
                    <%= link_to 'Delete your profile', user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item disabled" href="#">Algo que no sirve</a>
                </div>
            <li>
            <% end %>
            
        </ul>

        <form class="form-inline my-2 my-lg-0">
            <% if logged_in? %>
                <%= link_to 'Logout', logout_path, class:"btn btn-outline-danger my-2 my-sm-0", method: :delete %>
            <% else %>
                <%= link_to 'Login', login_path, class:"btn btn-outline-success my-2 my-sm-0" %>
            <% end %>
        </form>
    </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="content">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
  
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<a href="..">Go to home page</a>

app/views/pages/home.html.erb
  <div class="jumbotron">
    <h1 class="display-4">α-Blog</h1>
    <p class="lead">Simple Rails app for educational purposes</p>
    <hr class="my-4">
    <p>Rails + Bootstrap</p>
    <% if not logged_in? %>
      <%= link_to 'Sign up', signup_path, class: "btn btn-success btn-lg" %>    
      <%= link_to 'Login', login_path, class: "btn btn-success btn-lg" %> 
    <% end %>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Errores! Corriga estos errores porfavor para crear un <%= obj.class.name.downcase %></h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" >
        <span aria-hidden="true">&times;</span>
      </button>
  </div>    
<% end %>
  

app/views/shared/_pagination.html.erb
<div class="flickr_pagination mb-5 mb-4 mt-4">
    <%= will_paginate obj, :container => false %>
</div>

app/views/users/_form.html.erb
<div class="container p-4  shadow mb-5 rounded" id="new-edit-form">
    <%= render 'shared/errors', obj: @user %>
    
    <%= form_with(model: @user,  local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :username, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
                <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Ingrese un usuario" %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label  text-light" %>
            <div class="col-10">
                <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Ingrese su correo" %>
            </div>
        </div>

        <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label  text-light" %>
            <div class="col-10">
                <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Ingrese su contraseña" %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg shadow rounded") %>
        </div>
    <% end %>
</div>
<%= link_to '[Cancel and return to the home]', users_path, class: "text-info text-center" %>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Lista de usuarios </h1>

<%= render 'shared/pagination', obj: @users %>


<div class="row">
    <% @users.each do |user| %>
        <div class="card text-center col-sm-4">
            <div class="card-header">
                Perfil de <%= user.username %>
            </div>
            <div class="card-body">
                <%= gravatar_for user, size: 200 %>
                <h5 class="card-title"> <%= user.username %> </h5>
                <p class="card-text"> Correo: <%= user.email %> </p>
                <p class="card-text"><%= pluralize(user.articles.count, "Articulo") %> </p>
                <%= link_to 'Show', user_path(user.id), class: "btn btn-outline-success" %>
                <% if logged_in? && (user == current_user || current_user.admin?) %>
                    <%= link_to 'Editar', edit_user_path(user.id), class: "btn btn-outline-info" %>
                    <%= link_to 'Delete', user_path(user.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                <% end %>
            </div>
            
            <div class="card-footer text-muted">
                Joined <%= time_ago_in_words(user.created_at) %> ago
            </div>  
        </div>
    <% end %>
</div>

<%= render 'shared/pagination', obj: @users %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for alpha blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200%>
<% if logged_in? && (@user == current_user || current_user.admin?) %>
    <div class="text-center mt-4"><%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %></div>
<% end %>
<h1 class="text-center mt-4"> Articulos publicados: <%= @user.username %></h1>

<%= render 'shared/pagination', obj: @articles %>

<%= render 'articles/articles', obj: @articles %>

<%= render 'shared/pagination', obj: @articles %>